### ISSUE TITLE
Serialise into classes?

### ISSUE THREAD

**Issue by emilebosch** [jhawthorn/rapidjson-ruby#10]
Thanks for making this super fast library!
Would be nice if we could serialize in classes directly. I.e we could pass a method/proc that constructs the classes on the json that has been given.  This would allow me to directly map it to my domain models!

```ruby
def deserialize(hash)
  return Person.new(hash) if hash[:type] == 'person'
  return Car.new(hash) if hash[:type] == 'car'
  hash
end
RapidJson.parse(json, deserialize: method(:deserialize))
```

**Comment by jhawthorn** [comment]
Thanks for the suggestion. I'm not too sure about it on initial glance.

It could be nice if we could use this as an alternative to the "additions" the standard json library has. But on the other hand I don't think this needs gem support as you could iterate through the parsed hash to perform that `deserialize` operation. We have a feature like this in `Marshal` and it has been a bit of work to iron out the bugs in so I'm not keen on adding it here.

At least at the moment I think this is better achieved by post-processing the parsed hash in Ruby.

**Comment by emilebosch** [comment]
I understand the concern, but alas the json documents are of such size that kind of the benefit of parsing the json dissapears when needing to iterate over it and instantiate the classes afterwards. It would be nice if that all happened on the C side. But maybe i can try in a seperate gem.
