### ISSUE TITLE
Tips on using rapidjson to power rendering jbuilder views?

### ISSUE THREAD

**Issue by epugh** [jhawthorn/rapidjson-ruby#17]
I have a array of 50,000 objects to render in json, and it takes a long itme...   Any suggestions on how to use make sure I am using rapidjson?  I did do this:

```
ActiveSupport::JSON::Encoding.json_encoder = RapidJSON::ActiveSupportEncoder
```

**Comment by byroot** [comment]
I'm unfamiliar with `jbuilder`, it's best asked there. 

But if you want to test it works, you can just decorate/edit `RapidJSON::ActiveSupportEncoder` to make it's it's called with the JSON payloads you expect.
